server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #\u58F0\u660E\u81EA\u5DF1\u662F\u670D\u52A1\u7AEF
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/