server:
  port: 8781

#\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#\u670D\u52A1\u540D\u79F0
spring:
  application:
    name: order-server

  #\u81EA\u5B9A\u4E49\u8D1F\u8F7D\u5747\u8861\u7B56\u7565
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule