server:
  port: 8781

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



#思杰redis
spring:
  application:
    name: order-server
  redis:
    host: 47.100.115.31
    port: 6379
  zipkin:
    base-url: http://47.100.115.31:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1

#自定义负载均衡策略
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#默认optons readtimeout是60，但是由于hystrix默认是1秒超时
#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

# hystrix 超时时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


#断路器仪表 暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"



