#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: order-server
  #获取配置信息
  cloud:
    config:
      discovery:
        #默认是false,要开启
        enabled: true
        #选择配置服务
        service-id: CONFIG-SERVER
      #指定获取的文件，order-server -test
      profile: test
      #建议用lable去区分环境，默认是lable是master分支
      label: master

  redis:
    host: 39.98.206.180
    port: 6379
    password: Tongfu#01
  zipkin:
    base-url: http://39.98.206.180:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: 39.98.206.180
    port: 5672
    username: guest
    password: guest
server:
  port: 8782





#自定义负载均衡策略
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#默认optons readtimeout是60，但是由于hystrix默认是1秒超时
#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

# hystrix 超时时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


#断路器仪表 暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"


