#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

spring:
  application:
    name: zuul-server
  #获取配置信息
  cloud:
    config:
      discovery:
        #默认是false,要开启
        enabled: true
        #选择配置服务
        service-id: CONFIG-SERVER
      #指定获取的文件，order-server -test
      profile: test
      #建议用lable去区分环境，默认是lable是master分支
      label: master
  #配置rabbitmq
  rabbitmq:
    host: 39.98.206.180
    port: 5672
    username: guest
    password: guest

# hystrix 超时时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000




#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

#默认一秒，如果延时可以稍微设长一点
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000