server:
  port: 8771


#服务名称
spring:
  application:
    name: product-server
  redis:
    host: 47.100.115.31
    port: 6379
  zipkin:
    base-url: http://47.100.115.31:9411/
  #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
  sleuth:
    sampler:
      probability: 1

#注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/